# Generated by Django 5.2.5 on 2025-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название тега')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
