# Generated by Django 5.2.5 on 2025-08-07 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0003_alter_tag_slug_alter_video_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='disliked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='watch_later_users',
            field=models.ManyToManyField(blank=True, related_name='later_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
