# Generated by Django 5.2.5 on 2025-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0004_alter_video_dislikers_alter_video_watch_later_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='denisvideo.tag', verbose_name='Теги'),
        ),
    ]
