# Generated by Django 5.2.5 on 2025-08-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0005_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
