# Generated by Django 5.2.5 on 2025-08-09 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0007_video_likers_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mkv', 'mov', 'wmv', 'webm', 'html5', 'mpeg'])], verbose_name='Видео файл'),
        ),
    ]
