# Generated by Django 5.2.5 on 2025-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0008_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
