# Generated by Django 5.2.5 on 2025-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denisvideo', '0009_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=512, unique=True),
        ),
    ]
