# Generated by Django 5.2.5 on 2025-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='users.channel', verbose_name='Подписки'),
        ),
    ]
